SYSTEM: matgen-band
SYMPREC: 1E-6
ISTART: 1
NWRITE: 2
LPETIM: F
ISPIN: 2
ICHARG: 11
ENCUT: 520
PREC: Accurate
LWAVE: F
LCHARG: F
ADDGRID: T
NPAR: 8
NBLOCK: 1
INIWAV: 1
ISMEAR: 0 
SIGMA: 0.05
ALGO: Very_Fast
NELM: 140
NELMIN: 6
EDIFF: 1E-04
NSW: 0
IBRION: -1
ISIF: 0
EDIFFG: -1E-03
POTIM: 0.05
LORBIT: 11
