SYSTEM: matgen-dos
ISTART: 1
ISPIN: 2
ICHARG: 11
ENCUT: 520
PREC: Accurate
LWAVE: F
LCHARG: F
ADDGRID: T
NPAR: 8
ISMEAR: 0 
SIGMA: 0.05
ALGO: Very_Fast
NELM: 200
NELMIN: 6
EDIFF: 1E-04
NSW: 0
IBRION: -1
ISIF: 2
EDIFFG: -1E-02
POTIM: 0.5
LORBIT: 11
NEDOS: 2001
WEIMIN: 0
SYMPEREC: 1E-6
