SYSTEM: matgen-relax
ISTART: 0
ENCUT: 520
PREC: Accurate
ADDGRID: T
NPAR: 8
NELM: 60
NELMIN: 6
EDIFF: 1E-05
IBRION: 1
ISIF: 3
EDIFFG: -1E-03
POTIM: 0.5
SYMPREC: 1E-6
ISYM: 2
ISPIN: 2
LREAL: F
NBLOCK: 1
INIWAV: 1
ISMEAR: 0
SIGMA: 0.05
ALGO: Normal
NSW: 40
LCORR: T.
AMIX: 0.1
BMIX: 1.2
