ISPIN: 2
LREAL: F
ENCUT: 520
PREC: Normal
LWAVE: F
LCHARG: F
ADDGRID: T
NPAR: 8
NBLOCK: 1
INIWAV: 1
ISMEAR: 0
SIGMA: 0.05
ALGO: Normal
NELM: 60
NELMIN: 6
EDIFF: 1E-04
NSW: 40
IBRION: 2
ISIF: 3
EDIFFG: -1E-03
POTIM: 0.05
LCORR: T.
AMIX: 0.1
BMIX: 1.2
