ISTART: 0
ISPIN: 2
LREAL: F
ENCUT: 520
PREC: Accurate
LWAVE: F
LCHARG: .F.
ADDGRID: .F.
NPAR: 8
NBLOCK: 1
INIWAV: 1
ISMEAR: 0
SIGMA: 0.05
ALGO: Normal
NELM: 140
NELMIN: 6
EDIFF: 1E-04
NSW: 0
IBRION: -1
ISIF: 2
EDIFFG: -1E-02
POTIM: 0.05
AMIX: 0.1
BMIX: 1.2
LCORR: T
WEIMIN: 0
LAECHG: T
LORBIT: 11
SYMPREC: 1E-6
LSORBIT: .T.
LNONCOLLINEAR: .T.
