SYSTEM: matgen-test-spin
ISTART: 0
ISPIN: 2
LREAL: Auto
ENCUT: 520
PREC: Normal
LWAVE: F
LCHARG: F
ADDGRID: T
NPAR: 8
ISMEAR: 0
SIGMA: 0.05
ALGO: Very_Fast
LDIAG: T
NELM: 20
NELMIN: 5
EDIFF: 1E-04
NSW: 0
IBRION: -1
ISIF: 0
EDIFFG: -1E-02
LCORR: T

